name: ntds_2019
channels:
  - dglteam
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # Created by running the following commands on Linux, macOS and Windows, then taking the common subset of dependencies.
  # conda create -n ntds_2019 python=3.7 jupyterlab git numpy scipy matplotlib-base pandas networkx pygsp scikit-learn pytorch cpuonly dgl -c dglteam -c pytorch -c conda-forge -c defaults --override-channels
  # conda env export --no-builds -n ntds_2019 > environment_linux.yml
  - attrs=19.1.0
  - backcall=0.1.0
  - bleach=3.1.0
  - ca-certificates=2019.9.11
  - cffi=1.12.3
  - cpuonly=1.0
  - cycler=0.10.0
  - decorator=4.4.0
  - defusedxml=0.5.0
  - dgl=0.3.1
  - entrypoints=0.3
  - freetype=2.10.0
  - git=2.23.0
  - intel-openmp=2019.4
  - ipykernel=5.1.2
  - ipython=7.8.0
  - ipython_genutils=0.2.0
  - jedi=0.15.1
  - jinja2=2.10.1
  - joblib=0.13.2
  - json5=0.8.5
  - jsonschema=3.0.2
  - jupyter_client=5.3.1
  - jupyter_core=4.4.0
  - jupyterlab=1.1.3
  - jupyterlab_server=1.0.6
  - kiwisolver=1.1.0
  - libblas=3.8.0
  - libcblas=3.8.0
  - liblapack=3.8.0
  - libpng=1.6.37
  - libsodium=1.0.17
  - markupsafe=1.1.1
  - matplotlib-base=3.1.1
  - mistune=0.8.4
  - mkl=2019.4
  - nbconvert=5.6.0
  - nbformat=4.4.0
  - networkx=2.3
  - ninja=1.9.0
  - notebook=6.0.1
  - numpy=1.15.4
  - openssl=1.1.1c
  - pandas=0.25.1
  - pandoc=2.7.3
  - pandocfilters=1.4.2
  - parso=0.5.1
  - pickleshare=0.7.5
  - pip=19.2.3
  - prometheus_client=0.7.1
  - prompt_toolkit=2.0.9
  - pycparser=2.19
  - pygments=2.4.2
  - pygsp=0.5.1
  - pyparsing=2.4.2
  - pyrsistent=0.15.4
  - python=3.7.3
  - python-dateutil=2.8.0
  - pytorch=1.2.0
  - pytz=2019.2
  - pyzmq=18.1.0
  - scikit-learn=0.21.3
  - scipy=1.3.1
  - send2trash=1.5.0
  - setuptools=41.2.0
  - six=1.12.0
  - sqlite=3.29.0
  - terminado=0.8.2
  - testpath=0.4.2
  - tornado=6.0.3
  - traitlets=4.3.2
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.6
  - zeromq=4.3.2
  - zlib=1.2.11

# PyTorch Geometric. Not easy to install due to compilation.
# conda activate ntds_2019
# pip install requests torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric
# - pip:
#   - chardet==3.0.4
#   - googledrivedownloader==0.4
#   - h5py==2.10.0
#   - idna==2.8
#   - isodate==0.6.0
#   - plyfile==0.7
#   - rdflib==4.2.2
#   - requests==2.22.0
#   - torch-cluster==1.4.4
#   - torch-geometric==1.3.1
#   - torch-scatter==1.3.1
#   - torch-sparse==0.4.0
#   - torch-spline-conv==1.1.0
#   - urllib3==1.25.3
